"use strict";
/* Kalandmester (GM) – campaign builder and manager for both systems. Loaded last; shares the main script's helpers.
   A campaign lives in S.camps and is saved with the characters. Book stat blocks load lazily from data/gm-<game>.js. */
const gm={loading:{}};
const G_TABS=[['over',b('Áttekintés','Overview')],['story',b('Történet','Story board')],['loc',b('Helyszínek','Locations')],['npc',b('Szereplők','NPCs')],['best',b('Bestiárium','Bestiary')],['enc',b('Csaták','Encounters')],['rules',b('Szabályok és infók','Rules & info')],['log',b('Napló','Journal')]];
const G_WSTEPS=[b('Rendszer','System'),b('Alapötlet','Concept'),b('Első helyszín','First location'),b('Szereplők','Cast'),b('Események','Events'),b('Első csata','First encounter')];
// D&D SRD 5.2.1 "XP Budget per Character" (low / moderate / high)
const XPB=[[50,75,100],[100,150,200],[150,225,400],[250,375,500],[500,750,1100],[600,1000,1400],[750,1300,1700],[1000,1700,2100],[1300,2000,2600],[1600,2300,3100],[1900,2900,4100],[2200,3700,4700],[2600,4200,5400],[2900,4900,6200],[3300,5400,7800],[3800,6100,9800],[4500,7200,11700],[5000,8700,14200],[5500,10700,17200],[6400,13200,22000]];
// Daggerheart SRD Battle Points cost per adversary type
const BP_COST={Minion:1,Social:1,Support:1,Horde:2,Ranged:2,Skulk:2,Standard:2,Leader:3,Bruiser:4,Solo:5};
const G_STATUS=[['todo',b('Tervezett','Planned')],['doing',b('Folyamatban','In play')],['done',b('Lezárva','Resolved')]];
const curCamp=()=>(S.camps||[]).find(k=>k.id===ui.camp)||null;
const G=()=>ui.g||(ui.g={tab:'over',loc:0,enc:0,q:'',bq:'',bkind:'adv',btier:'',nq:''});
function gNeed(game){const key=game==='dnd'?'GM_DND':'GM_DH';if(window[key])return true;
 if(!gm.loading[game])gm.loading[game]=loadScript('data/gm-'+game+'.js').then(()=>{gm.loading[game]='ok';render()},()=>{gm.loading[game]='err';render()});return false}
function gNewCamp(game){const t=Date.now();return {id:'k-'+uid6(),kind:'camp',game,createdAt:t,updatedAt:t,creating:0,name:'',pitch:'',tone:'',themes:'',notes:'',locations:[],npcs:[],story:[],encounters:[],rules:[],info:[],prices:[],sessions:[],log:[],party:[],fear:0,countdowns:[]}}
function gNormalize(k){const d=gNewCamp(k.game||'dh');for(const f in d)if(k[f]==null&&f!=='creating'&&f!=='id')k[f]=d[f];if(k.creating===undefined)k.creating=null;k.kind='camp';return k}
const G_NEW={locations:()=>({id:uid6(),name:'',desc:'',senses:'',secret:'',notes:'',env:'',pcs:[]}),npcs:()=>({id:uid6(),name:'',role:'',wants:'',desc:'',notes:'',locId:'',att:'neutral',status:'alive',ref:''}),
 story:()=>({id:uid6(),title:'',text:'',status:'todo',locId:''}),encounters:()=>({id:uid6(),name:'',locId:'',notes:'',combatants:[],round:1,turn:0}),rules:()=>({id:uid6(),title:'',text:''}),info:()=>({id:uid6(),title:'',text:''}),
 prices:()=>({id:uid6(),name:'',price:'',note:''}),sessions:()=>({id:uid6(),date:new Date().toISOString().slice(0,10),title:'',prep:'',summary:''}),countdowns:()=>({name:'',val:4})};

/* ---------- book stat blocks ---------- */
const gBook=game=>game==='dnd'?(window.GM_DND||{mon:[]}).mon:(window.GM_DH||{adv:[]}).adv;
const gEnvs=()=>(window.GM_DH||{env:[]}).env;
const gFind=(game,name)=>gBook(game).find(x=>x.name===name)||null;
const crTxt=c=>c===0.125?'1/8':c===0.25?'1/4':c===0.5?'1/2':String(c);
const gTag=(game,x)=>game==='dnd'?`CR ${crTxt(x.cr)}`:`T${x.tier} ${x.type}`;
const gFeats=a=>(a||[]).map(f=>`<p><b>${esc(f.name||f.n)}.</b> ${mdl(f.text||f.d||'')}</p>`).join('');
function gStat(game,x){if(!x)return '';
 if(game==='dnd'){const mod=v=>sgn(Math.floor((v-10)/2));
  return `<div class="statblk"><p class="small"><em>${esc(x.size)} ${esc(x.type)}, ${esc(x.align||'')}</em></p><p><b>AC</b> ${x.ac} · <b>HP</b> ${x.hp} (${esc(x.hd||'')}) · <b>Speed</b> ${esc(x.speed)}</p>
   <div class="scroll"><table class="abil"><tr>${['STR','DEX','CON','INT','WIS','CHA'].map(a=>`<th>${a}</th>`).join('')}</tr><tr>${x.abil.map(v=>`<td class="num">${v} (${mod(v)})</td>`).join('')}</tr></table></div>
   <p class="small">${[x.saves&&`<b>Saves</b> ${esc(x.saves)}`,x.skills&&`<b>Skills</b> ${esc(x.skills)}`,x.vuln&&`<b>Vulnerabilities</b> ${esc(x.vuln)}`,x.res&&`<b>Resistances</b> ${esc(x.res)}`,x.imm&&`<b>Immunities</b> ${esc(x.imm)}`,x.senses&&`<b>Senses</b> ${esc(x.senses)}`,x.lang&&`<b>Languages</b> ${esc(x.lang)}`,`<b>CR</b> ${crTxt(x.cr)} (XP ${x.xp}; PB ${sgn(x.pb)})`].filter(Boolean).join(' · ')}</p>
   ${gFeats(x.traits)}${x.actions.length?`<h4>Actions</h4>${gFeats(x.actions)}`:''}${x.bonus.length?`<h4>Bonus Actions</h4>${gFeats(x.bonus)}`:''}${x.reactions.length?`<h4>Reactions</h4>${gFeats(x.reactions)}`:''}${x.legendary.length?`<h4>Legendary Actions</h4>${gFeats(x.legendary)}`:''}</div>`}
 return `<div class="statblk"><p class="small"><em>Tier ${x.tier} ${esc(x.type)}</em> — ${esc(x.desc)}</p><p class="small"><b>Motives &amp; Tactics:</b> ${esc(x.motives)}</p>
  <p><b>Difficulty</b> ${x.diff} · <b>Thresholds</b> ${esc(x.thr)} · <b>HP</b> ${x.hp} · <b>Stress</b> ${x.stress}</p><p><b>ATK</b> ${esc(x.atk)} · <b>${esc(x.attack)}</b>: ${esc(x.range)} · ${esc(x.damage)}</p>${x.exp?`<p class="small"><b>Experience:</b> ${esc(x.exp)}</p>`:''}${gFeats(x.feat)}</div>`}
const gStatEnv=e=>e?`<div class="statblk"><p class="small"><em>Tier ${e.tier} ${esc(e.type)}</em> — ${esc(e.desc)}</p><p class="small"><b>Impulses:</b> ${esc(e.impulses)}</p><p><b>Difficulty</b> ${e.diff}</p><p class="small"><b>Potential Adversaries:</b> ${esc(e.adv)}</p>${gFeats(e.feat)}</div>`:'';
function gCombatant(game,x){return game==='dnd'?{id:uid6(),name:x.name,ref:x.name,hpMax:x.hp,hp:x.hp,ac:x.ac,init:null,dex:Math.floor((x.abil[1]-10)/2),xp:x.xp}:{id:uid6(),name:x.name,ref:x.name,hpMax:+x.hp||1,hp:0,stressMax:+x.stress||0,stress:0,diff:x.diff,thr:x.thr,type:x.type}}
/** search box + the best matches from the book, each with one action button */
function gQuick(k,act,label,extra){const g=G(),q=g.bq.trim().toLowerCase();if(!gNeed(k.game))return gLoading(k.game);
 const list=q?gBook(k.game).filter(x=>(x.name+' '+x.type).toLowerCase().includes(q)).slice(0,8):[];
 return `<div class="row"><input type="search" id="gq_${act}" class="grow" data-ui="g.bq" data-live value="${esc(g.bq)}" placeholder="${L('Keresés a könyv szereplői között (angol név vagy típus)…','Search the book\'s creatures (name or type)…')}"></div>
 ${q?`<div class="row" style="margin-top:6px">${list.map(x=>`<button class="btn sm" data-act="${act}" data-n="${esc(x.name)}" ${extra||''}>+ ${esc(x.name)} <span class="muted">${gTag(k.game,x)}</span></button>`).join('')||`<span class="muted small">${L('Nincs találat.','No match.')}</span>`}</div>`:`<p class="small muted" style="margin-top:4px">${label}</p>`}`}
const gLoading=game=>`<p class="${gm.loading[game]==='err'?'note d':'muted'}">${gm.loading[game]==='err'?L('A könyvbeli szereplők betöltése nem sikerült.','Could not load the book creatures.'):L('Könyvbeli szereplők betöltése…','Loading book creatures…')}</p>`;
const gLocOpts=k=>[['',L('— nincs helyszínhez kötve —','— no location —')],...k.locations.map(l=>[l.id,l.name||L('Névtelen helyszín','Unnamed location')])];
const gLocName=(k,id)=>{const l=k.locations.find(x=>x.id===id);return l?(l.name||L('Névtelen helyszín','Unnamed location')):''};
const gDel=(c,i,key)=>`<button class="btn sm warn" data-act="gRm" data-c="${c}" data-i="${i}">${ui.confirm===key?L('Biztos?','Sure?'):'×'}</button>`;

/* ---------- home section ---------- */
function gHome(){const g=S.game,list=(S.camps||[]).filter(k=>k.game===g);
 return `<h2 style="margin-top:8px">${L('Kampányaid (kalandmester)','Your campaigns (game master)')} · ${gameName(g)} <span class="muted num">${list.length}</span></h2>
 <div class="row"><button class="btn pri big" data-act="gNew">+ ${L('Új kampány létrehozása','Create a new campaign')}</button></div>
 ${list.length?`<div class="cgrid">${list.map(k=>`<button type="button" class="ccard camp" data-act="gOpen" data-id="${k.id}"><span class="cport"><span>${esc((k.name||'?').trim()[0]||'?')}</span></span><span class="cinfo"><b>${esc(k.name||L('Névtelen kampány','Unnamed campaign'))}</b><span>${k.locations.length} ${L('helyszín','locations')} · ${k.npcs.length} ${L('szereplő','NPCs')} · ${k.encounters.length} ${L('csata','encounters')}</span><span class="cmeta">${k.creating!=null?L('félkész – folytasd az alkotást','unfinished – continue creating'):L('módosítva: ','edited ')+new Date(k.updatedAt).toLocaleDateString(lang==='hu'?'hu-HU':'en-GB')}</span></span></button>`).join('')}</div>`
 :`<div class="panel"><p class="muted">${L('Még nincs kampányod ebben a rendszerben. Az alkotó lépésről lépésre végigvezet az első helyszín és az ottani események megalkotásán.','No campaigns in this system yet. The creator walks you through building the first location and what happens there.')}</p></div>`}`}

/* ---------- creator wizard ---------- */
function gWizard(k){const s=k.creating,loc=k.locations[0];let body='';
 if(s===0)body=`<p class="small muted">${L('Melyik rendszerben mesélsz? Ettől függ, melyik könyv szereplői, szabályai és csataeszközei jelennek meg.','Which system do you run? It decides which book\'s creatures, rules and encounter tools you get.')}</p>
  <div class="gamesel" style="margin:8px 0">${GAMES.map(x=>`<button type="button" data-act="gGame" data-g="${x[0]}" aria-pressed="${k.game===x[0]}">${x[1]}</button>`).join('')}</div>${lab(L('A kampány címe','Campaign title'),fText('name',L('pl. A Fehér Láng örökösei','e.g. Heirs of the White Flame'),'data-re'))}`;
 if(s===1)body=`<div class="stack">${lab(L('Miről szól a kampány egy-két mondatban?','What is the campaign about, in a sentence or two?'),fArea('pitch',L('Kik a hősök, mi fenyegeti a világukat, miért épp ők?','Who are the heroes, what threatens their world, why them?'),3))}
  <div class="grid g2">${lab(L('Hangulat','Tone'),fText('tone',L('pl. sötét mese, könnyed kaland, nyomozós','e.g. dark fairy tale, light-hearted, mystery')))}${lab(L('Fő témák','Main themes'),fText('themes',L('pl. bosszú, hűség, elveszett örökség','e.g. revenge, loyalty, a lost legacy')))}</div>
  <p class="small muted">${L('Tipp: elég egy erős helyzet és egy megválaszolatlan kérdés. A többit a játék hozza.','Tip: one strong situation and one unanswered question is enough. Play brings the rest.')}</p></div>`;
 if(s===2&&loc)body=`<div class="stack">${lab(L('A helyszín neve','Location name'),fText('locations.0.name',L('pl. Hollókő fogadó','e.g. The Ravenstone Inn'),'data-re'))}
  ${k.game==='dh'?(gNeed('dh')?lab(T('Kiindulás egy könyvbeli környezetből (nem kötelező)','Start from a book environment (optional)'),`<select id="g_env0" data-chg="gEnvPick" data-i="0"><option value="">—</option>${gEnvs().map(e=>`<option value="${esc(e.name)}" ${loc.env===e.name?'selected':''}>${esc(e.name)} · T${e.tier} ${esc(e.type)}</option>`).join('')}</select>`):gLoading('dh')):''}
  ${lab(L('Mi ez a hely, és miért érkeznek ide a hősök?','What is this place, and why do the heroes come here?'),fArea('locations.0.desc','',3))}
  ${lab(L('Mit látnak, hallanak, éreznek, amikor megérkeznek?','What do they see, hear and feel on arrival?'),fArea('locations.0.senses','',2))}
  ${lab(L('Mi a hely titka – amit csak te tudsz?','What is the place\'s secret – the thing only you know?'),fArea('locations.0.secret','',2))}
  ${loc.env&&gFind&&gEnvs().find(e=>e.name===loc.env)?`<details><summary class="small">${esc(loc.env)} – ${L('a könyv leírása','book entry')}</summary>${gStatEnv(gEnvs().find(e=>e.name===loc.env))}</details>`:''}</div>`;
 if(s===3&&loc){const here=k.npcs.map((n,i)=>[n,i]).filter(q=>q[0].locId===loc.id);
  body=`<p class="small muted">${L('Kik vannak ezen a helyen? Két-három szereplő elég: valaki, aki segít, valaki, aki akadályoz, és valaki, aki többet tud, mint amit mond.','Who is at this place? Two or three are enough: someone who helps, someone who hinders, someone who knows more than they say.')}</p>
  <div class="list" style="margin-top:8px">${here.map(([n,i])=>`<div class="li"><span class="grow">${fText('npcs.'+i+'.name',L('Név','Name'))}</span><span class="grow">${fText('npcs.'+i+'.role',L('Szerep (pl. fogadós)','Role (e.g. innkeeper)'))}</span><span class="grow">${fText('npcs.'+i+'.wants',L('Mit akar?','What do they want?'))}</span>${n.ref?`<span class="tag">${esc(n.ref)}</span>`:''}${gDel('npcs',i,'npcs'+i)}</div>`).join('')}</div>
  <div class="row" style="margin:8px 0"><button class="btn sm pri" data-act="gAdd" data-c="npcs" data-loc="${loc.id}">+ ${L('Saját szereplő','Own NPC')}</button></div>
  ${gQuick(k,'gNpcBook',L('Írj be egy nevet, hogy a könyv egyik szereplőjét tedd ide (az értékeivel együtt).','Type a name to place one of the book\'s creatures here (with its stat block).'),`data-loc="${loc.id}"`)}`}
 if(s===4&&loc){const ev=k.story.map((e,i)=>[e,i]).filter(q=>q[0].locId===loc.id);
  body=`<p class="small muted">${L('Mi történik itt? Az események a történettáblára kerülnek, a helyszínhez kötve.','What happens here? Events go on the story board, tied to this location.')}</p>
  <div class="row" style="margin:8px 0">${[[L('Nyitójelenet','Opening scene'),L('Hogyan csöppennek bele a hősök?','How do the heroes get pulled in?')],[L('Bonyodalom','Complication'),L('Mi megy félre, ki áll az útjukba?','What goes wrong, who stands in the way?')],[L('Fordulat','Twist'),L('Mi derül ki, ami mindent megváltoztat?','What comes to light that changes everything?')],[L('Jutalom és továbblépés','Reward and way forward'),L('Mit nyernek, és hová vezet tovább a szál?','What do they gain, and where does the thread lead?')]].map(q=>`<button class="btn sm" data-act="gAdd" data-c="story" data-loc="${loc.id}" data-title="${esc(q[0])}" data-ph="${esc(q[1])}">+ ${q[0]}</button>`).join('')}<button class="btn sm" data-act="gAdd" data-c="story" data-loc="${loc.id}">+ ${L('Saját esemény','Own event')}</button></div>
  <div class="stack">${ev.map(([e,i])=>`<div class="card"><div class="row"><span class="grow">${fText('story.'+i+'.title',L('Az esemény címe','Event title'),'style="font-weight:700"')}</span>${gDel('story',i,'story'+i)}</div>${fArea('story.'+i+'.text',e.ph||L('Mi történik, és mi a tét?','What happens, and what is at stake?'),3)}</div>`).join('')||`<p class="muted">${L('Még nincs esemény – válassz fent egy sablont.','No events yet – pick a prompt above.')}</p>`}</div>`}
 if(s===5&&loc){const ei=k.encounters.findIndex(e=>e.locId===loc.id);
  body=ei<0?`<p class="small muted">${L('Nem kötelező, de ha várható összecsapás, most előkészítheted: a lap kiszámolja, mennyire nehéz.','Optional – if a fight is likely, prepare it now: the sheet estimates how hard it is.')}</p><div class="row" style="margin-top:8px"><button class="btn pri" data-act="gAdd" data-c="encounters" data-loc="${loc.id}">+ ${L('Csata előkészítése ezen a helyszínen','Prepare an encounter here')}</button></div>`
  :`${lab(L('A csata neve','Encounter name'),fText('encounters.'+ei+'.name',L('pl. Rajtaütés a pincében','e.g. Ambush in the cellar')))}<div style="margin-top:8px">${gBudget(k,k.encounters[ei])}</div>
   <div class="list" style="margin:8px 0">${k.encounters[ei].combatants.map((q,j)=>`<div class="li"><b class="grow">${esc(q.name)}</b>${q.ref&&gFind(k.game,q.ref)?`<span class="tag">${gTag(k.game,gFind(k.game,q.ref))}</span>`:''}<button class="btn sm warn" data-act="gCombRm" data-e="${ei}" data-j="${j}">×</button></div>`).join('')}</div>${gQuick(k,'gEncBook',L('Írj be egy nevet, hogy ellenfelet adj a csatához.','Type a name to add an adversary to the encounter.'),`data-e="${ei}"`)}`}
 return `<section class="blk"><div class="row"><h2 class="grow">${L('Kampányalkotó','Campaign creator')}${s>0?' · '+gameName(k.game):''}</h2><div class="steps">${G_WSTEPS.map((x,i)=>`<span class="${i===s?'cur':''}">${i+1}. ${P(x)}</span>`).join('')}</div></div>
 <div class="panel"><h3>${s+1}. ${N(G_WSTEPS[s])}</h3>${body}</div>
 <div class="row"><button class="btn" data-act="gWiz" data-d="-1" ${s===0?'disabled':''}>← ${L('Vissza','Back')}</button><span class="grow"></span><button class="btn warn" data-act="gDelCamp">${ui.confirm==='gdel'?L('Biztosan törlöd?','Really delete?'):L('Elvetés','Discard')}</button>
 ${s<5?`<button class="btn pri" data-act="gWiz" data-d="1">${L('Tovább','Next')} →</button>`:`<button class="btn pri" data-act="gWizDone">${L('Kész – nyisd meg a kampányt','Done – open the campaign')}</button>`}</div></section>`}

/* ---------- tabs ---------- */
function gSearch(k,q){const out=[],t=q.trim().toLowerCase();if(t.length<2)return out;const hit=(...a)=>a.join(' \n ').toLowerCase().includes(t);
 const snip=(...a)=>{const s=a.filter(Boolean).join(' · ').replace(/\s+/g,' '),p=Math.max(0,s.toLowerCase().indexOf(t)-40);return (p?'…':'')+s.slice(p,p+140)};
 k.locations.forEach((x,i)=>hit(x.name,x.desc,x.senses,x.secret,x.notes)&&out.push({tab:'loc',k:'loc',i,label:L('Helyszín','Location')+': '+(x.name||'—'),s:snip(x.desc,x.secret,x.notes)}));
 k.npcs.forEach((x,i)=>hit(x.name,x.role,x.wants,x.desc,x.notes,x.ref)&&out.push({tab:'npc',nq:x.name,label:L('Szereplő','NPC')+': '+(x.name||'—'),s:snip(x.role,x.wants,x.desc,x.notes)}));
 k.story.forEach((x,i)=>hit(x.title,x.text)&&out.push({tab:'story',label:L('Esemény','Event')+': '+(x.title||'—'),s:snip(x.text)}));
 k.encounters.forEach((x,i)=>hit(x.name,x.notes,x.combatants.map(c=>c.name).join(' '))&&out.push({tab:'enc',k:'enc',i,label:L('Csata','Encounter')+': '+(x.name||'—'),s:snip(x.combatants.map(c=>c.name).join(', '),x.notes)}));
 k.rules.forEach(x=>hit(x.title,x.text)&&out.push({tab:'rules',label:L('Házi szabály','House rule')+': '+(x.title||'—'),s:snip(x.text)}));
 k.info.forEach(x=>hit(x.title,x.text)&&out.push({tab:'rules',label:L('Infó','Info')+': '+(x.title||'—'),s:snip(x.text)}));
 k.prices.forEach(x=>hit(x.name,x.price,x.note)&&out.push({tab:'rules',label:L('Ár','Price')+': '+(x.name||'—'),s:snip(x.price,x.note)}));
 k.sessions.forEach(x=>hit(x.title,x.prep,x.summary)&&out.push({tab:'log',label:L('Session','Session')+': '+(x.title||x.date),s:snip(x.summary,x.prep)}));
 k.log.forEach(x=>hit(x.x)&&out.push({tab:'log',label:L('Naplósor','Log line'),s:snip(x.x)}));return out}
function gParty(k){return k.party.map(id=>S.chars.find(c=>c.id===id)).filter(Boolean)}
function gOver(k){const g=G(),res=gSearch(k,g.q),chars=S.chars.filter(c=>(c.game||'dh')===k.game&&!c.example),party=gParty(k);
 return `<section class="blk"><div class="panel"><h2>${L('Keresés a kampányban','Search the campaign')}</h2><input type="search" id="g_q" data-ui="g.q" data-live value="${esc(g.q)}" placeholder="${L('Helyszín, szereplő, esemény, szabály, naplóbejegyzés…','Location, NPC, event, rule, journal entry…')}">
  ${g.q.trim().length>1?`<div class="reslist" style="margin-top:8px">${res.map((r,i)=>`<a class="res" href="#" data-act="gGo" data-tab="${r.tab}" data-k="${r.k||''}" data-i="${r.i!=null?r.i:''}" data-nq="${esc(r.nq||'')}"><b>${esc(r.label)}</b><br><span class="small">${esc(r.s)}</span></a>`).join('')||`<p class="small muted" style="padding:8px">${L('Nincs találat.','No match.')}</p>`}</div>`:''}</div>
 <div class="grid g2"><div class="panel"><h2>${L('A kampány','The campaign')}</h2><div class="stack">${lab(L('Cím','Title'),fText('name','','data-re'))}${lab(L('Alapötlet','Concept'),fArea('pitch','',3))}<div class="grid g2">${lab(L('Hangulat','Tone'),fText('tone',''))}${lab(L('Témák','Themes'),fText('themes',''))}</div>${lab(L('Mesélői jegyzetek, hosszú távú tervek','GM notes, long-term plans'),fArea('notes','',4))}
   <div class="row"><span class="tag">${gameName(k.game)}</span><span class="small muted">${k.locations.length} ${L('helyszín','locations')} · ${k.npcs.length} ${L('szereplő','NPCs')} · ${k.story.length} ${L('esemény','events')} · ${k.encounters.length} ${L('csata','encounters')}</span><span class="grow"></span><button class="btn sm" data-act="gExport">${L('Kampány mentése fájlba','Save campaign to a file')}</button><button class="btn sm warn" data-act="gDelCamp">${ui.confirm==='gdel'?L('Biztosan törlöd? Kattints újra.','Really delete? Click again.'):L('Kampány törlése','Delete campaign')}</button></div></div></div>
  <div class="stack"><div class="panel"><h2>${L('Követők','Trackers')}</h2>${k.game==='dh'?`<div class="row"><b>${T('Félelem','Fear')}</b><span class="num muted">${k.fear}/12</span></div><div class="pips">${Array.from({length:12},(_,i)=>`<button type="button" class="pip stress ${i<k.fear?'on':''}" data-act="gFear" data-i="${i}" aria-label="${i+1}"></button>`).join('')}</div>`:''}
    <h3 style="margin-top:10px">${T('Visszaszámlálók, órák','Countdowns, clocks')}</h3><div class="list" style="margin-top:6px">${k.countdowns.map((c,i)=>`<div class="li"><span class="grow">${fText('countdowns.'+i+'.name',L('Mi közeleg?','What is coming?'))}</span>${stepper('countdowns.'+i+'.val',0,99)}${gDel('countdowns',i,'countdowns'+i)}</div>`).join('')}<div><button class="btn sm" data-act="gAdd" data-c="countdowns">+ ${L('Visszaszámláló','Countdown')}</button></div></div></div>
   <div class="panel"><h2>${L('A csapat','The party')}</h2><p class="small muted">${L('Az ezen a gépen lévő karakterlapok közül jelölheted ki a játékosok hőseit (a játékos JSON-fájlban is elküldheti a lapját).','Pick the players\' heroes from the sheets on this device (a player can also send their sheet as a JSON file).')}</p>
    <div class="row" style="margin-top:6px">${chars.map(c=>`<button class="btn sm ${k.party.includes(c.id)?'fear':''}" data-act="gParty" data-id="${c.id}">${esc(c.name||'?')} · ${esc(charCls(c))} ${c.level}</button>`).join('')||`<span class="muted small">${L('Ebben a rendszerben még nincs karakterlap ezen a gépen.','No character sheets in this system on this device yet.')}</span>`}</div>
    ${party.length?`<div class="scroll" style="margin-top:8px"><table><tr><th>${L('Hős','Hero')}</th><th>${L('Szint','Lvl')}</th>${k.game==='dnd'?'<th>AC</th><th>HP</th><th>PP</th>':`<th>${L('Kitérés','Evasion')}</th><th>${L('ÉP','HP')}</th><th>${L('Stressz','Stress')}</th><th>${L('Remény','Hope')}</th>`}<th></th></tr>${party.map(c=>{const d=derive(c);return `<tr><td><b>${esc(c.name||'?')}</b></td><td class="num">${c.level}</td>${!d?'<td colspan="3" class="muted">…</td>':k.game==='dnd'?`<td class="num">${d.ac.v}</td><td class="num">${d.hp}/${d.hpMax.v}</td><td class="num">${d.pp}</td>`:`<td class="num">${d.evasion.v}</td><td class="num">${c.hp}/${d.hpS.v}</td><td class="num">${c.stress}/${d.stS.v}</td><td class="num">${c.hope}</td>`}<td><button class="btn sm" data-act="openChar" data-id="${c.id}">${L('Lap','Sheet')}</button></td></tr>`}).join('')}</table></div>`:''}</div></div></div></section>`}
function gStory(k){return `<section class="blk"><div class="board">${G_STATUS.map((st,si)=>{const cards=k.story.map((e,i)=>[e,i]).filter(q=>q[0].status===st[0]);
  return `<div class="col"><div class="row"><h2 class="grow">${N(st[1])} <span class="muted num">${cards.length}</span></h2><button class="btn sm" data-act="gAdd" data-c="story" data-status="${st[0]}">+</button></div>
  ${cards.map(([e,i])=>`<div class="card"><div class="row">${si>0?`<button class="btn sm" data-act="gMove" data-i="${i}" data-d="-1" aria-label="←">←</button>`:''}<span class="grow">${fText('story.'+i+'.title',L('Cím','Title'),'style="font-weight:700"')}</span>${si<2?`<button class="btn sm" data-act="gMove" data-i="${i}" data-d="1" aria-label="→">→</button>`:''}</div>
   ${fArea('story.'+i+'.text',L('Mi történik, mi a tét, mi lehet a kimenetele?','What happens, what is at stake, how might it end?'),3)}<div class="row">${fSel('story.'+i+'.locId',gLocOpts(k),'style="width:auto;max-width:100%"')}<span class="grow"></span>${gDel('story',i,'story'+i)}</div></div>`).join('')||`<p class="muted small">${L('Üres.','Empty.')}</p>`}</div>`}).join('')}</div></section>`}
function gLoc(k){const g=G();g.loc=clamp(g.loc,0,Math.max(0,k.locations.length-1));const l=k.locations[g.loc],i=g.loc;
 const head=`<div class="row"><h2 class="grow">${L('Helyszínek','Locations')} <span class="muted num">${k.locations.length}</span></h2><button class="btn pri sm" data-act="gAdd" data-c="locations">+ ${L('Új helyszín','New location')}</button></div><div class="row" style="margin-top:8px">${k.locations.map((x,j)=>`<button class="btn sm ${j===i?'fear':''}" data-act="gSel" data-k="loc" data-i="${j}">${esc(x.name||L('Névtelen','Unnamed'))}</button>`).join('')}</div>`;
 if(!l)return `<section class="blk"><div class="panel">${head}<p class="muted" style="margin-top:8px">${L('Még nincs helyszín. Egy helyszín: ahol a szereplők összegyűlhetnek, és ahol valami történik.','No locations yet. A location is where characters gather and something happens.')}</p></div></section>`;
 const npcs=k.npcs.map((n,j)=>[n,j]).filter(q=>q[0].locId===l.id),ev=k.story.map((e,j)=>[e,j]).filter(q=>q[0].locId===l.id),enc=k.encounters.map((e,j)=>[e,j]).filter(q=>q[0].locId===l.id),party=gParty(k),env=k.game==='dh'&&l.env&&gNeed('dh')?gEnvs().find(e=>e.name===l.env):null;
 return `<section class="blk"><div class="panel">${head}</div><div class="grid g2"><div class="panel"><div class="stack">${lab(L('Név','Name'),fText('locations.'+i+'.name','','data-re'))}${lab(L('Leírás – mi ez a hely?','Description – what is this place?'),fArea('locations.'+i+'.desc','',3))}${lab(L('Érzékek – mit látnak, hallanak, éreznek?','Senses – what do they see, hear, feel?'),fArea('locations.'+i+'.senses','',2))}${lab(L('Titok – amit csak a mesélő tud','Secret – GM eyes only'),fArea('locations.'+i+'.secret','',2))}${lab(L('Jegyzetek','Notes'),fArea('locations.'+i+'.notes','',3))}
   ${k.game==='dh'?(gNeed('dh')?lab(T('Könyvbeli környezet','Book environment'),`<select id="g_env${i}" data-chg="gEnvPick" data-i="${i}"><option value="">—</option>${gEnvs().map(e=>`<option value="${esc(e.name)}" ${l.env===e.name?'selected':''}>${esc(e.name)} · T${e.tier} ${esc(e.type)}</option>`).join('')}</select>`):gLoading('dh')):''}${env?`<details open><summary class="small">${esc(env.name)}</summary>${gStatEnv(env)}</details>`:''}
   <div class="row"><span class="grow"></span>${gDel('locations',i,'locations'+i)}</div></div></div>
  <div class="stack"><div class="panel"><h2>${L('Kik vannak itt?','Who is here?')}</h2>${party.length?`<p class="small muted">${L('A csapat tagjai – kattints, ha itt vannak:','Party members – click if they are here:')}</p><div class="row" style="margin:6px 0">${party.map(c=>`<button class="btn sm ${l.pcs.includes(c.id)?'pri':''}" data-act="gHere" data-i="${i}" data-id="${c.id}">${esc(c.name||'?')}</button>`).join('')}</div>`:''}
    <div class="list">${npcs.map(([n,j])=>`<div class="li"><b class="grow">${esc(n.name||L('Névtelen','Unnamed'))}</b><span class="small muted">${esc(n.role)}</span>${n.ref?`<span class="tag">${esc(n.ref)}</span>`:''}<button class="btn sm" data-act="gGo" data-tab="npc" data-nq="${esc(n.name)}">${L('Megnyit','Open')}</button></div>`).join('')||`<span class="muted small">${L('Nincs itt szereplő.','No NPCs here.')}</span>`}</div>
    <div class="row" style="margin-top:8px"><button class="btn sm" data-act="gAdd" data-c="npcs" data-loc="${l.id}" data-go="npc">+ ${L('Szereplő ide','NPC here')}</button></div></div>
   <div class="panel"><h2>${L('Események itt','Events here')}</h2><div class="list">${ev.map(([e,j])=>`<div class="li"><span class="tag ${e.status==='done'?'g':e.status==='doing'?'h':''}">${P(G_STATUS.find(s=>s[0]===e.status)[1])}</span><b class="grow">${esc(e.title||'—')}</b></div>`).join('')||`<span class="muted small">—</span>`}</div><div class="row" style="margin-top:8px"><button class="btn sm" data-act="gAdd" data-c="story" data-loc="${l.id}" data-go="story">+ ${L('Esemény ide','Event here')}</button></div></div>
   <div class="panel"><h2>${L('Csaták itt','Encounters here')}</h2><div class="list">${enc.map(([e,j])=>`<div class="li"><b class="grow">${esc(e.name||L('Névtelen csata','Unnamed encounter'))}</b><span class="small muted">${e.combatants.length} ${L('résztvevő','combatants')}</span><button class="btn sm" data-act="gGo" data-tab="enc" data-k="enc" data-i="${j}">${L('Megnyit','Open')}</button></div>`).join('')||`<span class="muted small">—</span>`}</div><div class="row" style="margin-top:8px"><button class="btn sm" data-act="gAdd" data-c="encounters" data-loc="${l.id}" data-go="enc">+ ${L('Csata ide','Encounter here')}</button></div></div></div></div></section>`}
function gNpc(k){const g=G(),q=g.nq.trim().toLowerCase(),list=k.npcs.map((n,i)=>[n,i]).filter(([n])=>!q||(n.name+' '+n.role+' '+n.ref+' '+gLocName(k,n.locId)).toLowerCase().includes(q));
 const att=[['friendly',L('barátságos','friendly')],['neutral',L('semleges','neutral')],['hostile',L('ellenséges','hostile')]],stt=[['alive',L('él','alive')],['dead',L('halott','dead')],['unknown',L('ismeretlen','unknown')]];
 return `<section class="blk"><div class="panel"><div class="row"><h2 class="grow">${L('Szereplők','NPCs')} <span class="muted num">${k.npcs.length}</span></h2><button class="btn pri sm" data-act="gAdd" data-c="npcs">+ ${L('Új szereplő','New NPC')}</button></div>
  <div class="row" style="margin-top:8px"><input type="search" id="g_nq" class="grow" data-ui="g.nq" data-live value="${esc(g.nq)}" placeholder="${L('Szűrés név, szerep, helyszín szerint…','Filter by name, role, location…')}"></div>
  <div style="margin-top:10px"><b class="small">${L('Könyvbeli szereplő felvétele','Add a creature from the book')}</b>${gQuick(k,'gNpcBook',L('Az értékeivel együtt kerül a kampányba; nevet, szerepet te adsz neki.','It joins the campaign with its stat block; you give it a name and a role.'))}</div></div>
 <div class="grid g2">${list.map(([n,i])=>{const st=n.ref&&gNeed(k.game)?gFind(k.game,n.ref):null;return `<div class="card npc ${n.status==='dead'?'vault':''}" style="--dom:var(--${n.att==='hostile'?'danger':n.att==='friendly'?'ok':'muted'})"><div class="row cardhead"><span class="grow">${fText('npcs.'+i+'.name',L('Név','Name'),'style="font-weight:700"')}</span>${gDel('npcs',i,'npcs'+i)}</div>
  <div class="grid g2">${lab(L('Szerep','Role'),fText('npcs.'+i+'.role',''))}${lab(L('Helyszín','Location'),fSel('npcs.'+i+'.locId',gLocOpts(k)))}${lab(L('Hozzáállás','Attitude'),fSel('npcs.'+i+'.att',att))}${lab(L('Állapot','Status'),fSel('npcs.'+i+'.status',stt))}</div>
  ${lab(L('Mit akar?','What do they want?'),fText('npcs.'+i+'.wants',''))}${lab(L('Leírás, modor, hang','Description, manner, voice'),fArea('npcs.'+i+'.desc','',2))}${lab(L('Jegyzetek – mit tud, mi történt vele','Notes – what they know, what happened'),fArea('npcs.'+i+'.notes','',2))}
  ${n.ref?`<details><summary class="small">${L('Könyvbeli értékek','Book stat block')}: ${esc(n.ref)}${st?' · '+gTag(k.game,st):''}</summary>${st?gStat(k.game,st):gLoading(k.game)}<div class="row" style="margin-top:6px"><button class="btn sm" data-act="gNpcToEnc" data-i="${i}">${L('Hozzáadás a kijelölt csatához','Add to the selected encounter')}</button></div></details>`:''}</div>`}).join('')||`<p class="muted">${k.npcs.length?L('Nincs a szűrésnek megfelelő szereplő.','No NPC matches the filter.'):L('Még nincs szereplő.','No NPCs yet.')}</p>`}</div></section>`}
function gBestiary(k){const g=G();if(!gNeed(k.game))return `<section class="blk"><div class="panel">${gLoading(k.game)}</div></section>`;const q=g.bq.trim().toLowerCase(),env=k.game==='dh'&&g.bkind==='env';
 const all=env?gEnvs():gBook(k.game),tiers=k.game==='dnd'?[...new Set(all.map(x=>x.cr))].sort((a,z)=>a-z):['1','2','3','4'];
 const list=all.filter(x=>(!q||(x.name+' '+x.type).toLowerCase().includes(q))&&(g.btier===''||String(k.game==='dnd'?x.cr:x.tier)===String(g.btier)));
 return `<section class="blk"><div class="panel"><h2>${T('Bestiárium','Bestiary')} · ${gameName(k.game)} <span class="muted num">${list.length}/${all.length}</span></h2><p class="small muted">${k.game==='dnd'?L('Az SRD 5.2.1 szörnyei és állatai teljes értékekkel.','The monsters and animals of SRD 5.2.1 with full stat blocks.'):L('A Daggerheart SRD ellenfelei és környezetei teljes értékekkel.','The adversaries and environments of the Daggerheart SRD with full stat blocks.')}</p>
  <div class="row" style="margin-top:8px">${k.game==='dh'?`<span class="row" style="gap:4px"><button class="btn sm ${!env?'fear':''}" data-act="gBk" data-v="adv">${T('Ellenfelek','Adversaries')}</button><button class="btn sm ${env?'fear':''}" data-act="gBk" data-v="env">${T('Környezetek','Environments')}</button></span>`:''}
   <input type="search" id="g_bq" class="grow" style="min-width:160px" data-ui="g.bq" data-live value="${esc(g.bq)}" placeholder="${L('Keresés név vagy típus szerint…','Search by name or type…')}"><select id="g_bt" data-ui="g.btier" style="width:auto"><option value="">${k.game==='dnd'?L('minden CR','any CR'):L('minden fokozat','any tier')}</option>${tiers.map(t=>`<option value="${t}" ${String(g.btier)===String(t)?'selected':''}>${k.game==='dnd'?'CR '+crTxt(t):'Tier '+t}</option>`).join('')}</select></div></div>
 <div class="panel"><div class="list">${list.slice(0,40).map(x=>`<div class="li top catrow"><details class="grow"><summary><span class="tag h">${env?'T'+x.tier:gTag(k.game,x)}</span> ${esc(x.name)} <span class="small muted" style="font-family:var(--body);font-weight:400">${esc(k.game==='dnd'?x.size+' '+x.type:x.type)}</span></summary>${env?gStatEnv(x):gStat(k.game,x)}</details>${env?'':`<div class="row" style="gap:4px"><button class="btn sm" data-act="gNpcBook" data-n="${esc(x.name)}">+ ${L('Szereplő','NPC')}</button><button class="btn sm pri" data-act="gEncBook" data-n="${esc(x.name)}">+ ${L('Csata','Fight')}</button></div>`}</div>`).join('')||`<p class="muted">${L('Nincs találat.','No match.')}</p>`}</div>${list.length>40?`<p class="small muted" style="margin-top:8px">${L('Az első 40 látszik – szűkíts a keresővel.','Showing the first 40 – narrow it with search.')}</p>`:''}</div></section>`}
function gBudget(k,e){const party=gParty(k),n=party.length||4;
 if(k.game==='dnd'){const lv=party.length?Math.round(party.reduce((q,c)=>q+(+c.level||1),0)/party.length):1,b=XPB[clamp(lv,1,20)-1].map(v=>v*n),xp=e.combatants.reduce((q,c)=>q+(c.pc?0:+c.xp||0),0),lab2=xp===0?'—':xp<=b[0]?L('könnyű','low'):xp<=b[1]?L('közepes','moderate'):xp<=b[2]?L('nehéz','high'):L('a nehéznél is több','beyond high');
  return `<p class="small"><b>${L('Nehézség','Difficulty')}:</b> ${xp} XP → <b>${lab2}</b> · ${L('keret','budget')} ${n} ${L('hősre','heroes')}, ${lv}. ${L('szint','level')}: ${b[0]} / ${b[1]} / ${b[2]} XP ${party.length?'':`<span class="muted">(${L('nincs kijelölt csapat – 4 fő, 1. szint','no party set – 4 heroes, level 1')})</span>`}</p>`}
 let minions=0,pts=0;e.combatants.forEach(c=>{if(c.pc)return;if(c.type==='Minion')minions++;else pts+=BP_COST[c.type]||2});pts+=Math.ceil(minions/n);const bud=3*n+2;
 return `<p class="small"><b>${T('Csatapontok','Battle Points')}:</b> ${pts} / ${bud} <span class="tag ${pts>bud+2?'d':pts>=bud-1?'h':'g'}">${pts>bud+2?L('nagyon nehéz','very hard'):pts>bud?L('nehezebb','harder'):pts>=bud-1?L('kiegyensúlyozott','balanced'):L('könnyebb','easier')}</span> ${party.length?'':`<span class="muted">(${L('nincs kijelölt csapat – 4 fővel számol','no party set – assumes 4 heroes')})</span>`}</p>`}
function gEnc(k){const g=G();g.enc=clamp(g.enc,0,Math.max(0,k.encounters.length-1));const e=k.encounters[g.enc],i=g.enc,dnd=k.game==='dnd';
 const head=`<div class="row"><h2 class="grow">${L('Csaták','Encounters')} <span class="muted num">${k.encounters.length}</span></h2><button class="btn pri sm" data-act="gAdd" data-c="encounters">+ ${L('Új csata','New encounter')}</button></div><div class="row" style="margin-top:8px">${k.encounters.map((x,j)=>`<button class="btn sm ${j===i?'fear':''}" data-act="gSel" data-k="enc" data-i="${j}">${esc(x.name||L('Névtelen','Unnamed'))}</button>`).join('')}</div>`;
 if(!e)return `<section class="blk"><div class="panel">${head}<p class="muted" style="margin-top:8px">${L('Még nincs előkészített csata.','No encounters prepared yet.')}</p></div></section>`;
 const rows=e.combatants.map((c,j)=>{const st=c.ref&&gNeed(k.game)?gFind(k.game,c.ref):null,pc=c.pc?S.chars.find(x=>x.id===c.pc):null,pd=pc?derive(pc):null,p=`encounters.${i}.combatants.${j}`,out=!c.pc&&(dnd?c.hp<=0:c.hp>=c.hpMax);
  return `<div class="comb ${dnd&&e.turn===j?'cur':''} ${out?'out':''}"><div class="row">${dnd?`<label class="chk small" title="${L('Kezdeményezés','Initiative')}">${L('Kezd.','Init')} <input type="number" id="${fid(p+'.init')}" data-bind="${p}.init" data-num value="${c.init==null?'':c.init}" style="width:4em"></label>`:`<button class="btn sm ${c.spot?'pri':''}" data-act="gSpot" data-j="${j}" title="${L('Reflektorfény: már sorra került','Spotlight: has acted')}">★</button>`}
   <b class="grow" style="flex-basis:9em">${esc(c.name)}${c.pc?` <span class="tag">${L('hős','PC')}</span>`:''}${out?` <span class="tag d">${L('legyőzve','defeated')}</span>`:''}</b>
   ${c.pc?(pd?`<span class="small num">${dnd?`AC ${pd.ac.v} · HP ${pd.hp}/${pd.hpMax.v}`:`${L('Kitérés','Evasion')} ${pd.evasion.v} · ${L('ÉP','HP')} ${pc.hp}/${pd.hpS.v}`}</span>`:''):dnd?`<span class="small num">AC ${c.ac}</span><span class="num"><b>${c.hp}</b>/${c.hpMax}</span><input type="number" id="gd_${j}" placeholder="±" style="width:4.2em" aria-label="${L('Sebzés vagy gyógyítás','Damage or healing')}"><button class="btn sm warn" data-act="gDmg" data-j="${j}" data-s="-1">${L('Sebzés','Dmg')}</button><button class="btn sm" data-act="gDmg" data-j="${j}" data-s="1">${L('Gyógy.','Heal')}</button>`
    :`<span class="small num">${L('Nehézség','Diff.')} ${c.diff||'—'} · ${esc(c.thr||'')}</span><span class="nw"><span class="small">${L('ÉP','HP')}</span>${stepper(p+'.hp',0,c.hpMax)}<span class="small muted num">/${c.hpMax}</span></span>${c.stressMax?`<span class="nw"><span class="small">${L('Stressz','Stress')}</span>${stepper(p+'.stress',0,c.stressMax)}<span class="small muted num">/${c.stressMax}</span></span>`:''}`}
   <button class="btn sm warn" data-act="gCombRm" data-e="${i}" data-j="${j}">×</button></div>${st?`<details><summary class="small">${L('Értékek','Stat block')} · ${gTag(k.game,st)}</summary>${gStat(k.game,st)}</details>`:''}</div>`}).join('');
 return `<section class="blk"><div class="panel">${head}</div><div class="grid g2"><div class="panel"><div class="stack">${lab(L('A csata neve','Encounter name'),fText('encounters.'+i+'.name','','data-re'))}${lab(L('Helyszín','Location'),fSel('encounters.'+i+'.locId',gLocOpts(k)))}${lab(L('Terep, taktika, tét, lehetséges kimenetelek','Terrain, tactics, stakes, possible outcomes'),fArea('encounters.'+i+'.notes','',4))}${gBudget(k,e)}
   <div><b class="small">${L('Ellenfél a könyvből','Adversary from the book')}</b>${gQuick(k,'gEncBook',L('Írj be egy nevet; többször is hozzáadhatod ugyanazt.','Type a name; you can add the same one several times.'),`data-e="${i}"`)}</div>
   <div class="row"><button class="btn sm" data-act="gEncParty">${L('A csapat hozzáadása','Add the party')}</button><button class="btn sm" data-act="gEncCustom">+ ${L('Saját résztvevő','Custom combatant')}</button><span class="grow"></span>${gDel('encounters',i,'encounters'+i)}</div></div></div>
  <div class="panel"><div class="row"><h2 class="grow">${L('Csatakövető','Combat tracker')}</h2>${dnd?`<span class="tag h">${L('Kör','Round')} ${e.round}</span><button class="btn sm" data-act="gInit">${L('Kezdeményezés dobása','Roll initiative')}</button><button class="btn sm pri" data-act="gNext">${L('Következő','Next turn')} →</button>`:`<button class="btn sm" data-act="gSpotClear">${L('Reflektorfény törlése','Clear spotlight marks')}</button>`}<button class="btn sm" data-act="gEncReset">${L('Alaphelyzet','Reset')}</button></div>
   ${!dnd?`<div class="row" style="margin-top:6px"><b>${T('Félelem','Fear')}</b>${stepper('fear',0,12)}<span class="small muted">${L('A mesélő Félelmet költ a reflektorfény átvételére és képességekre.','Spend Fear to seize the spotlight and fuel features.')}</span></div>`:''}
   <div class="stack" style="margin-top:10px;gap:8px">${rows||`<p class="muted">${L('Adj résztvevőket a csatához a bal oldalon.','Add combatants on the left.')}</p>`}</div></div></div></section>`}
function gRules(k){const dnd=k.game==='dnd',g=G();let cat='';
 if(dnd){if(dNeed('data')){const q=(g.pq||'').trim().toLowerCase(),all=[...DND.gear,...DND.weapons,...DND.armor].filter(x=>x.cost),hit=q?all.filter(x=>x.name.toLowerCase().includes(q)).slice(0,12):[];
   cat=`<div style="margin-top:10px"><b class="small">${L('Könyvbeli árak (SRD)','Book prices (SRD)')}</b><div class="row"><input type="search" id="g_pq" class="grow" data-ui="g.pq" data-live value="${esc(g.pq||'')}" placeholder="${L('pl. rope, longsword, potion…','e.g. rope, longsword, potion…')}"></div>${q?`<div class="row" style="margin-top:6px">${hit.map(x=>`<button class="btn sm" data-act="gPriceAdd" data-n="${esc(x.name)}" data-p="${esc(x.cost)}">${esc(x.name)} · <b>${esc(x.cost)}</b></button>`).join('')||`<span class="muted small">${L('Nincs találat.','No match.')}</span>`}</div><p class="small muted">${L('Kattintásra a saját árlistádra kerül.','Click to copy onto your own price list.')}</p>`:''}</div>`}else cat=dLoading('data')}
 const block=(c,title,ph1,ph2)=>`<div class="panel"><div class="row"><h2 class="grow">${title} <span class="muted num">${k[c].length}</span></h2><button class="btn sm pri" data-act="gAdd" data-c="${c}">+</button></div><div class="stack" style="margin-top:8px">${k[c].map((x,i)=>`<div class="card"><div class="row"><span class="grow">${fText(c+'.'+i+'.title',ph1,'style="font-weight:700"')}</span>${gDel(c,i,c+i)}</div>${fArea(c+'.'+i+'.text',ph2,3)}</div>`).join('')||`<p class="muted small">${L('Még üres.','Empty so far.')}</p>`}</div></div>`;
 return `<section class="blk"><div class="panel"><h2>${L('Szabálykönyv','Rulebook')} · ${gameName(k.game)}</h2><div class="row"><input type="search" id="g_rq" class="grow" data-ui="g.rq" value="${esc(g.rq||'')}" placeholder="${L('Keresés a szabálykönyvben (angolul)…','Search the rulebook…')}"><button class="btn pri" data-act="gRuleSearch">${L('Keresés','Search')}</button><button class="btn" data-act="gRuleSearch" data-open="1">${L('Szabálykönyv megnyitása','Open the rulebook')}</button></div>
  <p class="small muted" style="margin-top:6px">${dnd?L('Hasznos fejezetek: Combat, Conditions (Rules Glossary), Equipment, Gameplay Toolbox (csapdák, mérgek, találkozók).','Handy chapters: Combat, Conditions (Rules Glossary), Equipment, Gameplay Toolbox (traps, poisons, encounters).'):L('Hasznos fejezetek: Core GM Mechanics, Adversaries and Environments, Conditions, Downtime, Gold.','Handy chapters: Core GM Mechanics, Adversaries and Environments, Conditions, Downtime, Gold.')}</p></div>
 <div class="grid g2">${block('rules',L('Házi szabályok (homebrew)','House rules (homebrew)'),L('A szabály neve','Rule name'),L('Mit változtat, mikor érvényes, miért?','What does it change, when does it apply, why?'))}${block('info',L('Fontos infók','Key information'),L('Cím (pl. a világ naptára, frakciók)','Title (e.g. calendar, factions)'),L('Amit mesélés közben gyorsan elő kell venned.','What you need at hand while running the game.'))}</div>
 <div class="panel"><div class="row"><h2 class="grow">${L('Árlista','Price list')} <span class="muted num">${k.prices.length}</span></h2><button class="btn sm pri" data-act="gAdd" data-c="prices">+ ${L('Tétel','Entry')}</button></div>
  ${!dnd?`<p class="small muted">${L('A Daggerheartban a vagyon marék / zsák / láda aranyban mérődik (10 marék = 1 zsák, 10 zsák = 1 láda); a könyv nem ad fix árlistát, ezért itt a sajátodat vezetheted.','Daggerheart measures wealth in handfuls / bags / chests of gold (10 handfuls = 1 bag, 10 bags = 1 chest); the book has no fixed price list, so keep your own here.')}</p>`:''}
  <div class="list" style="margin-top:8px">${k.prices.map((x,i)=>`<div class="li"><span class="grow">${fText('prices.'+i+'.name',L('Mi?','What?'))}</span><span style="flex:0 1 9em">${fText('prices.'+i+'.price',L('Ár','Price'))}</span><span class="grow">${fText('prices.'+i+'.note',L('Megjegyzés','Note'))}</span>${gDel('prices',i,'prices'+i)}</div>`).join('')}</div>${cat}</div></section>`}
function gLog(k){return `<section class="blk"><div class="panel"><h2>${L('Gyors napló','Quick log')}</h2><div class="row"><input type="text" id="g_logline" class="grow" placeholder="${L('Mi történt most? (Enter)','What just happened? (Enter)')}"><button class="btn pri" data-act="gLogAdd">+</button></div>
  <div class="hist" style="margin-top:8px">${k.log.slice().reverse().map(e=>`<div><time>${new Date(e.t).toLocaleDateString(lang==='hu'?'hu-HU':'en-GB')} ${hhmm(e.t)}</time>${esc(e.x)}</div>`).join('')||`<span class="muted">${L('A csatakövető eseményei és a saját soraid kerülnek ide.','Combat tracker events and your own lines appear here.')}</span>`}</div></div>
 <div class="panel"><div class="row"><h2 class="grow">${L('Sessionök','Sessions')} <span class="muted num">${k.sessions.length}</span></h2><button class="btn pri sm" data-act="gAdd" data-c="sessions">+ ${L('Új session','New session')}</button></div></div>
 ${k.sessions.map((x,i)=>[x,i]).reverse().map(([x,i])=>`<details class="panel" ${i===k.sessions.length-1?'open':''}><summary>${i+1}. ${esc(x.title||L('Session','Session'))} <span class="muted small num">${esc(x.date)}</span></summary><div class="stack"><div class="grid g2">${lab(L('Cím','Title'),fText('sessions.'+i+'.title',''))}${lab(L('Dátum','Date'),`<input type="date" id="${fid('sessions.'+i+'.date')}" data-bind="sessions.${i}.date" value="${esc(x.date)}">`)}</div>
  ${lab(L('Felkészülés – jelenetek, titkok, nyitva hagyott szálak','Prep – scenes, secrets, loose threads'),fArea('sessions.'+i+'.prep','',4))}${lab(L('Összefoglaló – mi történt valójában?','Recap – what actually happened?'),fArea('sessions.'+i+'.summary','',4))}<div class="row"><span class="grow"></span>${gDel('sessions',i,'sessions'+i)}</div></div></details>`).join('')}</section>`}
function gView(){const k=curCamp();if(!k)return '';if(k.creating!=null)return gWizard(k);return ({over:gOver,story:gStory,loc:gLoc,npc:gNpc,best:gBestiary,enc:gEnc,rules:gRules,log:gLog}[G().tab]||gOver)(k)}

/* ---------- actions ---------- */
const gLogLine=(k,x)=>{k.log.push({t:Date.now(),x});if(k.log.length>400)k.log.splice(0,k.log.length-400)};
const gEncSel=k=>{const g=G();if(!k.encounters.length){k.encounters.push(G_NEW.encounters());g.enc=0}return k.encounters[clamp(g.enc,0,k.encounters.length-1)]};
Object.assign(A,{
 gNew(){const k=gNewCamp(S.game);S.camps.push(k);ui.camp=k.id;ui.view='camp';ui.g=null;touch(k);render();window.scrollTo(0,0)},
 gOpen(x){ui.camp=x.id;ui.view='camp';ui.g=null;ui.imp=false;render();window.scrollTo(0,0)},
 gTab(x){G().tab=x.t;render();window.scrollTo(0,0)},
 gGame(x){const k=curCamp();k.game=x.g;touch(k);render()},
 gWiz(x){const k=curCamp();k.creating=clamp(k.creating+ +x.d,0,5);if(k.creating>=2&&!k.locations.length)k.locations.push(G_NEW.locations());G().bq='';touch(k);render();window.scrollTo(0,0)},
 gWizDone(){const k=curCamp();k.creating=null;ui.g=null;touch(k);render();window.scrollTo(0,0)},
 gDelCamp(){if(ui.confirm!=='gdel'){ui.confirm='gdel';return render()}ui.confirm=null;const k=curCamp();S.camps=S.camps.filter(x=>x.id!==k.id);S.deleted.push(k.id);
  if(db){db.collection(base).doc(k.id).delete().catch(()=>{});db.collection(base).doc('meta-deleted').set({ids:S.deleted}).catch(()=>{})}ui.view='home';saveLocal();render();window.scrollTo(0,0)},
 gAdd(x){const k=curCamp(),it=G_NEW[x.c]();if(x.loc)it.locId=x.loc;if(x.title)it.title=x.title;if(x.ph)it.ph=x.ph;if(x.status)it.status=x.status;k[x.c].push(it);const g=G();
  if(x.c==='locations'){g.loc=k.locations.length-1}if(x.c==='encounters'){g.enc=k.encounters.length-1}if(x.go){g.tab=x.go;if(x.go==='npc')g.nq=''}touch(k);render()},
 gRm(x){const key=x.c+x.i;if(ui.confirm!==key){ui.confirm=key;return render()}ui.confirm=null;const k=curCamp(),it=k[x.c][+x.i];k[x.c].splice(+x.i,1);
  if(x.c==='locations'&&it){[...k.npcs,...k.story,...k.encounters].forEach(q=>{if(q.locId===it.id)q.locId=''})}touch(k);render()},
 gSel(x){G()[x.k]=+x.i;render()},
 gGo(x){const g=G();g.tab=x.tab;if(x.k&&x.i!=='')g[x.k]=+x.i;if(x.tab==='npc')g.nq=x.nq||'';render();window.scrollTo(0,0)},
 gMove(x){const k=curCamp(),e=k.story[+x.i],o=G_STATUS.map(s=>s[0]);e.status=o[clamp(o.indexOf(e.status)+ +x.d,0,2)];touch(k);render()},
 gEnvPick(x,el){const k=curCamp(),l=k.locations[+x.i];l.env=el.value;const e=gEnvs().find(q=>q.name===el.value);if(e){if(!l.name)l.name=e.name;if(!l.desc)l.desc=e.desc}touch(k);render()},
 gFear(x){const k=curCamp(),i=+x.i;k.fear=k.fear===i+1?i:i+1;touch(k);render()},
 gParty(x){const k=curCamp();k.party=k.party.includes(x.id)?k.party.filter(i=>i!==x.id):[...k.party,x.id];touch(k);render()},
 gHere(x){const k=curCamp(),l=k.locations[+x.i];l.pcs=l.pcs.includes(x.id)?l.pcs.filter(i=>i!==x.id):[...l.pcs,x.id];touch(k);render()},
 gBk(x){const g=G();g.bkind=x.v;g.btier='';render()},
 gNpcBook(x){const k=curCamp(),n=G_NEW.npcs();n.name=x.n;n.ref=x.n;n.att='hostile';if(x.loc)n.locId=x.loc;k.npcs.push(n);if(k.creating==null){const g=G();g.tab='npc';g.nq=x.n}touch(k);render()},
 gEncBook(x){const k=curCamp(),st=gFind(k.game,x.n);if(!st)return;const e=x.e!=null&&x.e!==''?k.encounters[+x.e]:gEncSel(k);e.combatants.push(gCombatant(k.game,st));touch(k);render()},
 gNpcToEnc(x){const k=curCamp(),n=k.npcs[+x.i],st=gFind(k.game,n.ref);if(!st)return;const c=gCombatant(k.game,st);c.name=n.name||st.name;gEncSel(k).combatants.push(c);G().tab='enc';touch(k);render()},
 gEncParty(){const k=curCamp(),e=gEncSel(k);gParty(k).forEach(c=>{if(!e.combatants.some(q=>q.pc===c.id))e.combatants.push({id:uid6(),name:c.name||'?',pc:c.id,init:null})});touch(k);render()},
 gEncCustom(){const k=curCamp(),e=gEncSel(k);e.combatants.push(k.game==='dnd'?{id:uid6(),name:L('Saját résztvevő','Custom combatant'),hpMax:10,hp:10,ac:10,init:null,dex:0,xp:0}:{id:uid6(),name:L('Saját ellenfél','Custom adversary'),hpMax:3,hp:0,stressMax:2,stress:0,diff:'12',thr:'',type:'Standard'});touch(k);render()},
 gCombRm(x){const k=curCamp();k.encounters[+x.e].combatants.splice(+x.j,1);touch(k);render()},
 gDmg(x){const k=curCamp(),e=gEncSel(k),c=e.combatants[+x.j],el=document.getElementById('gd_'+x.j),n=Math.abs(parseInt(el&&el.value,10)||0);if(!n||!c||c.pc)return;c.hp=clamp(c.hp+ +x.s*n,0,c.hpMax);
  gLogLine(k,`${e.name||L('Csata','Encounter')}: ${c.name} ${+x.s<0?L('sebződik','takes'):L('gyógyul','heals')} ${n} → ${c.hp}/${c.hpMax}${c.hp<=0?L(' – legyőzve',' – defeated'):''}`);touch(k);render()},
 gInit(){const k=curCamp(),e=gEncSel(k);e.combatants.forEach(c=>{if(c.pc){if(c.init==null){const pc=S.chars.find(q=>q.id===c.pc),d=pc?derive(pc):null;c.init=rnd(20)+(d&&d.init?d.init.v:0)}}else c.init=rnd(20)+(+c.dex||0)});
  e.combatants.sort((p,q)=>(q.init||0)-(p.init||0));e.round=1;e.turn=0;gLogLine(k,`${e.name||L('Csata','Encounter')}: ${L('kezdeményezés','initiative')} – ${e.combatants.map(c=>`${c.name} ${c.init}`).join(', ')}`);touch(k);render()},
 gNext(){const k=curCamp(),e=gEncSel(k),n=e.combatants.length;if(!n)return;let t=e.turn;for(let s=0;s<n;s++){t++;if(t>=n){t=0;e.round++}const c=e.combatants[t];if(c.pc||c.hp>0)break}e.turn=t;touch(k);render()},
 gSpot(x){const k=curCamp(),c=gEncSel(k).combatants[+x.j];c.spot=!c.spot;touch(k);render()},
 gSpotClear(){const k=curCamp();gEncSel(k).combatants.forEach(c=>c.spot=false);touch(k);render()},
 gEncReset(){if(ui.confirm!=='gres'){ui.confirm='gres';return render()}ui.confirm=null;const k=curCamp(),e=gEncSel(k);e.round=1;e.turn=0;e.combatants.forEach(c=>{c.spot=false;c.init=null;if(!c.pc){c.hp=k.game==='dnd'?c.hpMax:0;if(c.stressMax!=null)c.stress=0}});touch(k);render()},
 gPriceAdd(x){const k=curCamp();k.prices.push({id:uid6(),name:x.n,price:x.p,note:''});touch(k);render()},
 gRuleSearch(x){const k=curCamp(),q=(G().rq||'').trim();S.game=k.game;ui.view='rules';if(k.game==='dnd'&&!dNeed('rules')){ui.pendingRuleQ=x.open?'':q;return render()}useRules(k.game);ui.rule.q=x.open?'':q;render();window.scrollTo(0,0)},
 gLogAdd(){const k=curCamp(),el=document.getElementById('g_logline');if(!el||!el.value.trim())return;gLogLine(k,el.value.trim());touch(k);render()},
 gExport(){const k=curCamp();saveFile(fileBase({name:k.name||'kampany'})+'-kampany.json',JSON.stringify(k,null,1),'application/json')}
});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='g_logline')A.gLogAdd();if(e.key==='Enter'&&e.target.id==='g_rq')A.gRuleSearch({})});

boot();
